In [3]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [4]:
df = pd.read_csv("../data/processed/processed_data.csv")

df.head()

,N,P,K,temperature,humidity,ph,rainfall,label
0,65.133280,62.570254,4.004397,30.443243,89.327208,6.326934,5.302620,papaya
1,15.007021,65.153569,2.958001,37.187407,55.412434,5.992015,4.811221,pigeonpeas
2,41.782840,24.319279,2.751183,31.119400,88.956764,7.284694,4.649512,orange
3,96.495746,21.001000,3.256222,23.881388,55.858852,6.490042,5.167702,coffee
4,106.096464,91.194900,3.901779,25.692974,83.944196,6.332409,4.751576,banana

In [5]:
df.shape

(20281, 8)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20281 entries, 0 to 20280
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   N            20281 non-null  float64
 1   P            20281 non-null  float64
 2   K            20281 non-null  float64
 3   temperature  20281 non-null  float64
 4   humidity     20281 non-null  float64
 5   ph           20281 non-null  float64
 6   rainfall     20281 non-null  float64
 7   label        20281 non-null  object
dtypes: float64(7), object(1)
memory usage: 1.2+ MB

In [7]:
df.isnull().sum()

N              0
P              0
K              0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64

In [8]:
df.describe()

,N,P,K,temperature,humidity,ph,rainfall
count,20281.000000,20281.000000,20281.000000,20281.000000,20281.000000,20281.000000,20281.000000
mean,50.556896,53.828321,3.547147,25.535232,73.193900,6.429507,4.487046
std,36.552516,34.105892,0.603596,4.986854,22.426576,0.746950,0.529374
min,0.867547,4.268002,1.679774,13.087838,19.312616,4.428372,2.924808
25%,21.764076,26.192339,3.079221,22.517179,62.381740,5.938911,4.169181
50%,37.046322,51.238217,3.603174,25.605228,81.267155,6.392539,4.579533
75%,84.958656,69.566335,3.935530,28.454020,89.095563,6.887582,4.797319
max,154.433076,138.303922,4.576070,37.878628,100.000000,8.407522,5.355480